name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2018.11.26
      - name: Test
        run: |
          echo "Installing pipenv dependencies"
          PIPENV_NOSPIN=true pipenv install --dev
          pipenv run test
